"""Shared constants for audiototext."""

DEFAULT_OUTPUT_FORMATS = ("txt", "vtt", "srt", "tsv", "json")
SUPPORTED_OUTPUT_FORMATS = set(DEFAULT_OUTPUT_FORMATS)

OPENAI_SUPPORTED_FORMATS = {"mp3", "mp4", "mpeg", "mpga", "m4a", "wav", "webm"}
OPENAI_MAX_BYTES = 25 * 1024 * 1024

WHISPER_MODELS = ("tiny", "base", "small", "medium", "large-v2", "turbo")
ENGLISH_ONLY_BASE_MODELS = {"tiny", "base", "small", "medium"}

WHISPER_LANGUAGE_CHOICES = (
    "Auto-Detect",
    "Afrikaans",
    "Albanian",
    "Amharic",
    "Arabic",
    "Armenian",
    "Assamese",
    "Azerbaijani",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Burmese",
    "Castilian",
    "Catalan",
    "Chinese",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Estonian",
    "Faroese",
    "Finnish",
    "Flemish",
    "French",
    "Galician",
    "Georgian",
    "German",
    "Greek",
    "Gujarati",
    "Haitian",
    "Haitian Creole",
    "Hausa",
    "Hawaiian",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Italian",
    "Japanese",
    "Javanese",
    "Kannada",
    "Kazakh",
    "Khmer",
    "Korean",
    "Lao",
    "Latin",
    "Latvian",
    "Letzeburgesch",
    "Lingala",
    "Lithuanian",
    "Luxembourgish",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Maori",
    "Marathi",
    "Moldavian",
    "Moldovan",
    "Mongolian",
    "Myanmar",
    "Nepali",
    "Norwegian",
    "Nynorsk",
    "Occitan",
    "Panjabi",
    "Pashto",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Pushto",
    "Romanian",
    "Russian",
    "Sanskrit",
    "Serbian",
    "Shona",
    "Sindhi",
    "Sinhala",
    "Sinhalese",
    "Slovak",
    "Slovenian",
    "Somali",
    "Spanish",
    "Sundanese",
    "Swahili",
    "Swedish",
    "Tagalog",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Tibetan",
    "Turkish",
    "Turkmen",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Valencian",
    "Vietnamese",
    "Welsh",
    "Yiddish",
    "Yoruba",
)

DEEPL_TARGET_LANGUAGES = (
    "Bulgarian",
    "Chinese",
    "Chinese (simplified)",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "English (American)",
    "English (British)",
    "Estonian",
    "Finnish",
    "French",
    "German",
    "Greek",
    "Hungarian",
    "Indonesian",
    "Italian",
    "Japanese",
    "Korean",
    "Latvian",
    "Lithuanian",
    "Norwegian",
    "Polish",
    "Portuguese",
    "Portuguese (Brazilian)",
    "Portuguese (European)",
    "Romanian",
    "Russian",
    "Slovak",
    "Slovenian",
    "Spanish",
    "Swedish",
    "Turkish",
    "Ukrainian",
)
